#!/usr/bin/env bash

# Interactive script to help find and configure all required OCI resources
# Usage: ./find-oci-resources.sh

set -euo pipefail

echo "🔧 Oracle Cloud Infrastructure Resource Finder"
echo "=============================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if OCI CLI is installed
if ! command -v oci &> /dev/null; then
    echo -e "${RED}❌ OCI CLI not found${NC}"
    echo ""
    echo "Please install OCI CLI first:"
    echo "  bash -c \"\$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)\""
    echo ""
    echo "Or visit: https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm"
    exit 1
fi

echo -e "${GREEN}✅ OCI CLI found${NC}"
echo ""

# Check if OCI CLI is configured
if [ ! -f ~/.oci/config ]; then
    echo -e "${YELLOW}⚠️  OCI CLI not configured${NC}"
    echo ""
    echo "Run: oci setup config"
    echo ""
    echo "Or manually create ~/.oci/config with your API key details"
    exit 1
fi

echo -e "${GREEN}✅ OCI CLI configured${NC}"
echo ""

# Get tenancy OCID from config
echo "🔍 Finding Tenancy OCID..."
TENANCY_OCID=$(oci iam tenancy get --tenancy-id "$(grep tenancy ~/.oci/config | cut -d= -f2 | tr -d ' ')" --query 'data.id' --raw-output 2>/dev/null || echo "")

if [ -z "$TENANCY_OCID" ]; then
    echo -e "${RED}❌ Could not get tenancy OCID${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Tenancy OCID:${NC} $TENANCY_OCID"
echo ""

# Get user OCID from config
echo "🔍 Finding User OCID..."
USER_OCID=$(grep user ~/.oci/config | head -1 | cut -d= -f2 | tr -d ' ')
echo -e "${GREEN}✅ User OCID:${NC} $USER_OCID"
echo ""

# Get fingerprint from config
echo "🔍 Finding API Key Fingerprint..."
FINGERPRINT=$(grep fingerprint ~/.oci/config | cut -d= -f2 | tr -d ' ')
echo -e "${GREEN}✅ Fingerprint:${NC} $FINGERPRINT"
echo ""

# Get region from config
echo "🔍 Finding Region..."
REGION=$(grep region ~/.oci/config | cut -d= -f2 | tr -d ' ')
echo -e "${GREEN}✅ Region:${NC} $REGION"
echo ""

# Get private key path
echo "🔍 Finding Private Key Path..."
KEY_FILE=$(grep key_file ~/.oci/config | cut -d= -f2 | tr -d ' ')
echo -e "${GREEN}✅ Private Key:${NC} $KEY_FILE"
echo ""

# List availability domains
echo "🔍 Finding Availability Domains..."
echo ""
ADS=$(oci iam availability-domain list --compartment-id "$TENANCY_OCID" --query 'data[*].name' --raw-output 2>/dev/null | tr '\t' '\n')

if [ -z "$ADS" ]; then
    echo -e "${RED}❌ Could not list availability domains${NC}"
    exit 1
fi

echo -e "${GREEN}Available Availability Domains:${NC}"
echo "$ADS" | nl
echo ""

# Get first AD as default
DEFAULT_AD=$(echo "$ADS" | head -1)
echo -e "${GREEN}✅ Default AD (first one):${NC} $DEFAULT_AD"
echo ""

# Find ARM image
echo "🔍 Finding latest ARM image for Oracle Linux 8..."
echo ""

ARM_IMAGE_OCID=$(oci compute image list \
    --compartment-id "$TENANCY_OCID" \
    --operating-system "Oracle Linux" \
    --operating-system-version "8" \
    --shape "VM.Standard.A1.Flex" \
    --sort-by TIMECREATED \
    --sort-order DESC \
    --limit 1 \
    --query 'data[0].id' \
    --raw-output 2>/dev/null || echo "")

if [ -z "$ARM_IMAGE_OCID" ] || [ "$ARM_IMAGE_OCID" = "null" ]; then
    echo -e "${YELLOW}⚠️  No ARM image found for this region${NC}"
    echo "You may need to try a different region"
    ARM_IMAGE_OCID="<CHANGE_ME>"
else
    IMAGE_NAME=$(oci compute image get \
        --image-id "$ARM_IMAGE_OCID" \
        --query 'data."display-name"' \
        --raw-output 2>/dev/null || echo "Unknown")
    echo -e "${GREEN}✅ ARM Image:${NC} $IMAGE_NAME"
    echo -e "${GREEN}   OCID:${NC} $ARM_IMAGE_OCID"
fi
echo ""

# Generate terraform.tfvars content
echo "=============================================="
echo "📋 Configuration Summary"
echo "=============================================="
echo ""

cat << EOF
tenancy_ocid        = "$TENANCY_OCID"
user_ocid           = "$USER_OCID"
fingerprint         = "$FINGERPRINT"
private_key_path    = "$KEY_FILE"
region              = "$REGION"
compartment_ocid    = "$TENANCY_OCID"  # Using tenancy as compartment (root)
availability_domain = "$DEFAULT_AD"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
arm_image_ocid      = "$ARM_IMAGE_OCID"
EOF

echo ""
echo "=============================================="
echo ""

# Offer to write to file
echo -e "${YELLOW}Would you like to write this to terraform.tfvars?${NC}"
read -p "This will overwrite any existing file. (yes/no): " -r REPLY
echo ""

if [[ $REPLY =~ ^[Yy]es$ ]]; then
    cat > terraform.tfvars << EOF
# Generated by find-oci-resources.sh on $(date)

tenancy_ocid        = "$TENANCY_OCID"
user_ocid           = "$USER_OCID"
fingerprint         = "$FINGERPRINT"
private_key_path    = "$KEY_FILE"
region              = "$REGION"
compartment_ocid    = "$TENANCY_OCID"  # Using tenancy as compartment (root)
availability_domain = "$DEFAULT_AD"
ssh_public_key_path = "~/.ssh/id_rsa.pub"
arm_image_ocid      = "$ARM_IMAGE_OCID"
EOF
    echo -e "${GREEN}✅ Written to terraform.tfvars${NC}"
    echo ""
else
    echo "Copy the configuration above manually to terraform.tfvars"
    echo ""
fi

echo "=============================================="
echo -e "${GREEN}🎉 Resource discovery complete!${NC}"
echo "=============================================="
echo ""
echo "Next steps:"
echo "  1. Review terraform.tfvars (or create it with the config above)"
echo "  2. Ensure ~/.ssh/id_rsa.pub exists (your SSH public key)"
echo "  3. Run: make install && make get"
echo "  4. Run: make plan"
echo "  5. Run: make deploy"
echo ""

